include = [
  ".rustfmt.toml",
  ".taplo.toml",
  "Cargo.toml",
  "crates/**/*.toml",
  "deny.toml",
  "docs/**/*.toml",
  "grafana/**/*.toml",
  "helm/**/*.toml",
  "k8s/**/*.toml",
  "prometheus/**/*.toml",
  "rust-toolchain.toml",
]

[formatting]
reorder_arrays = true
reorder_keys = true
